### ISSUE TITLE
@State decorator

### ISSUE THREAD

**Issue by KerryRitter** [Lodin/ng-metasys#1]
Love this project!

I think most people are using ui-router at this point and I was thinking that adding a @State decorator to hook up a ui-router state/route would be excellent.

**Comment by Lodin** [comment]
Done by 99745c6.

@KerryRitter take a look at [ngms-plugin-ui-router-states](https://github.com/Lodin/ngms-plugin-ui-router-states). It allows using `ui-router` along with `ng-metasys`.
